annotations:
  anybuild.run/config:
    commands:
      start: uvicorn a:app --interface=wsgi --host 0.0.0.0 --port $PORT
    name: out
    python_cross_platform: wasix_wasm32
    python_extra_dependencies:
      - uvicorn
    python_extra_index_url: https://pythonindex.wasix.org/simple
    python_framework: flask
    python_install_inputs:
      - pyproject.toml
      - README.md
    python_main_file: app.py
    python_server: uvicorn
    wsgi_application: a:app
locality:
  regions:
    - fr-roub1
volumes:
  - name: studyai_data
    mount: /data
